### ISSUE TITLE
"From" name issue

### ISSUE THREAD

**Issue by samer** [webdigi/GmailScheduler#20]
If I am called John Doe and my email address is john.doe@example.org, the email will appear as if it were sent by john.doe instead of John Doe. I'm using this script on a Google Apps domain. Any idea why this is happening?

**Comment by erave02** [comment]
Same here

**Comment by webdigi** [comment]
Thanks for the comment. Will add this to next version.

**Comment by jsl** [comment]
Hi @webdigi,

Thanks for contributing this program.

This issue was a show-stopper for me, so I took a stab at fixing it myself. This PR works for me in a test environment that I set up. It may fail if the sender doesn't have a name defined before the email address, but I'm not sure if this is possible in Gmail. Can you take a look and let me know what you think?

Thanks!
